# docker run -d --rm --name mongo -p 27017:27017 -v mongodbdata:/data/db mongo
# docker-compose up

version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
