# docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=yourStrong(!)Password" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest

version: '3.9'
services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    environment:
      SA_PASSWORD: 'UPlower123!@#'
      ACCEPT_EULA: 'Y'
    ports:
      - 1433:1433
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
